version: 2
jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
    steps:
      - checkout
      - run: npm ci
      - run: npm run start &
      - run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: npm run cy:pipeline
